### ISSUE TITLE
Error "ProcessField: You need to select a resource and save field before start to use Mystique."

### ISSUE THREAD

**Issue by jlahijani** [trk/Mystique#10]
I have an issue that is occurring only on one particular installation of ProcessWire.  I can't replicate this issue on another installation.  I've tried deleting all my Mystique fields, reinstalling the module, disabling other modules, removing hooks, and a bunch of other things, but I really can't figure out why I'm getting this error only on this installation.

When I create a new field (using Mystique) and hit save, I get this error:
```
Error "ProcessField: You need to select a resource and save field before start to use Mystique."
```

This error occurs also when trying to edit any other field once I've created that buggy field, whether it's Mystique or not.

Now, if I edit my database manually (using phpmyadmin) and assign the resource, it will work.

To delete the field, I have to temporarily edit /src/MystiqueValue.php and disable line 93.  The error goes away allowing me to remove the field so my site doesn't break.

Any ideas what this could be and if possible, is there some sort of fix that can be implemented?

Debug backtrace:
```
DEBUG MODE BACKTRACE ($config->debug == true):
#0 /alef-dev/site/modules/Mystique/FieldtypeMystique.module.php(73): Altivebir\Mystique\MystiqueValue->__construct(Object(ProcessWire\NullPage), Object(ProcessWire\Field))
#1 /processwire-dev/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module(1054): ProcessWire\FieldtypeMystique->getBlankValue(Object(ProcessWire\NullPage), Object(ProcessWire\Field))
#2 /processwire-dev/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module(943): ProcessWire\InputfieldSelector->renderSelectFieldOption(Object(ProcessWire\Field), Array, '')
#3 /processwire-dev/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module(1923): ProcessWire\InputfieldSelector->renderSelectField(Array)
#4 /processwire-dev/wire/core/Wire.php(394): ProcessWire\InputfieldSelector->___render()
#5 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#6 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldSelector), 'render', Array)
#7 /processwire-dev/wire/core/InputfieldWrapper.php(912): ProcessWire\Wire->__call('render', Array)
#8 /processwire-dev/wire/core/Wire.php(400): ProcessWire\InputfieldWrapper->___renderInputfield(Object(ProcessWire\InputfieldSelector), false)
#9 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___renderInputf...', Array)
#10 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldFieldset), 'renderInputfiel...', Array)
#11 /processwire-dev/wire/core/InputfieldWrapper.php(592): ProcessWire\Wire->__call('renderInputfiel...', Array)
#12 /processwire-dev/wire/modules/Inputfield/InputfieldFieldset.module(18): ProcessWire\InputfieldWrapper->___render()
#13 /processwire-dev/wire/core/Wire.php(394): ProcessWire\InputfieldFieldset->___render()
#14 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#15 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldFieldset), 'render', Array)
#16 /processwire-dev/wire/core/InputfieldWrapper.php(912): ProcessWire\Wire->__call('render', Array)
#17 /processwire-dev/wire/core/Wire.php(400): ProcessWire\InputfieldWrapper->___renderInputfield(Object(ProcessWire\InputfieldFieldset), false)
#18 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___renderInputf...', Array)
#19 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldWrapper), 'renderInputfiel...', Array)
#20 /processwire-dev/wire/core/InputfieldWrapper.php(592): ProcessWire\Wire->__call('renderInputfiel...', Array)
#21 /processwire-dev/wire/core/Wire.php(394): ProcessWire\InputfieldWrapper->___render()
#22 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#23 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldWrapper), 'render', Array)
#24 /processwire-dev/wire/core/InputfieldWrapper.php(912): ProcessWire\Wire->__call('render', Array)
#25 /processwire-dev/wire/core/Wire.php(400): ProcessWire\InputfieldWrapper->___renderInputfield(Object(ProcessWire\InputfieldWrapper), false)
#26 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___renderInputf...', Array)
#27 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldForm), 'renderInputfiel...', Array)
#28 /processwire-dev/wire/core/InputfieldWrapper.php(592): ProcessWire\Wire->__call('renderInputfiel...', Array)
#29 /processwire-dev/wire/modules/Inputfield/InputfieldForm.module(144): ProcessWire\InputfieldWrapper->___render()
#30 /processwire-dev/wire/core/Wire.php(394): ProcessWire\InputfieldForm->___render()
#31 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#32 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldForm), 'render', Array)
#33 /processwire-dev/wire/modules/Process/ProcessField/ProcessField.module(783): ProcessWire\Wire->__call('render', Array)
#34 /processwire-dev/wire/core/Wire.php(394): ProcessWire\ProcessField->___executeEdit()
#35 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___executeEdit', Array)
#36 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessField), 'executeEdit', Array)
#37 /processwire-dev/wire/core/ProcessController.php(337): ProcessWire\Wire->__call('executeEdit', Array)
#38 /processwire-dev/wire/core/Wire.php(394): ProcessWire\ProcessController->___execute()
#39 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___execute', Array)
#40 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessController), 'execute', Array)
#41 /processwire-dev/wire/core/admin.php(160): ProcessWire\Wire->__call('execute', Array)
#42 /processwire-dev/wire/modules/AdminTheme/AdminThemeUikit/controller.php(15): require('/p...')
#43 /alef-dev/site/templates/admin.php(381): require('/p...')
#44 /processwire-dev/wire/core/TemplateFile.php(318): require('/a...')
#45 /processwire-dev/wire/core/Wire.php(394): ProcessWire\TemplateFile->___render()
#46 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#47 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#48 /processwire-dev/wire/modules/PageRender.module(536): ProcessWire\Wire->__call('render', Array)
#49 /processwire-dev/wire/core/Wire.php(397): ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#50 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___renderPage', Array)
#51 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#52 /processwire-dev/wire/core/WireHooks.php(924): ProcessWire\Wire->__call('renderPage', Array)
#53 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\DefaultPage), 'render', Array)
#54 /processwire-dev/wire/modules/Process/ProcessPageView.module(221): ProcessWire\Wire->__call('render', Array)
#55 /processwire-dev/wire/core/Wire.php(397): ProcessWire\ProcessPageView->___execute(true)
#56 /processwire-dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod('___execute', Array)
#57 /processwire-dev/wire/core/Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#58 /alef-dev/index.php(55): ProcessWire\Wire->__call('execute', Array)
#59 {main}
```

Tested on PW 3.0.170 and latest version of Mystique.

**Comment by trk** [comment]
on some of servers, getting mystique config files may have problem. i updated finding config files method on [next](https://github.com/trk/Mystique/tree/next) branch, can you test [next](https://github.com/trk/Mystique/tree/next) version on this server ?
